--- 
abstract: Allow bulk editing of custom fields
author: 
  - Alex Vandiver <alexmv@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.70
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RTx-RT34-Bulk-CF-Edit
no_index: 
  directory: 
    - etc
    - html
    - po
    - var
    - inc
requires: 
  Test::More: 0
version: 0.002
